### ISSUE TITLE
editors clear and other components disappear on save sometimes

### ISSUE THREAD

**Issue by estherhersh** [peblio/proto-2#120]
<img width="1421" alt="screen shot 2018-01-09 at 7 31 55 pm" src="https://user-images.githubusercontent.com/14132409/34754634-fa1804be-f58c-11e7-86fc-d4632f58f100.png">

**Comment by MathuraMG** [comment]
@estherhersh - this is super weird, does this happen randomly?

**Comment by estherhersh** [comment]
@MathuraMG - I'm trying to figure out what causes is but yeah it seems to be random

**Comment by estherhersh** [comment]
<img width="1382" alt="screen shot 2018-01-09 at 10 50 02 pm" src="https://user-images.githubusercontent.com/14132409/34755017-78e9ca1e-f58f-11e7-8615-c97c5327a2fe.png">

I think there's some confusion when you try running a p5 and a js editor or possibly two of the same....this just happened after trying to run both

**Comment by MathuraMG** [comment]
@estherhersh  - Im not able to replicate this, I have 3 editors and it works. Can we video call to see it in yours?

**Comment by MathuraMG** [comment]
@estherhersh - is this related to #119 ?

**Comment by MathuraMG** [comment]
@mbryk - were you able to replicate the error? I'm still unable to do so :\

**Comment by mbryk** [comment]
Nope - I misunderstood the bug. I'm seeing a different issue related to currentTextEditor state, which happens when you click from one text editor into another text editor. I'll fix it tomorrow when I look more into separating editorStates...

**Comment by MathuraMG** [comment]
hey @mbryk ! what exactly is the issue you are seeing?

**Comment by MathuraMG** [comment]
I dont think this is an issue now, Im going to close this
